### ISSUE TITLE
estimate potential throughput for corenlp annotation

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#12]
The geotagging is capable of handling about a million stories per day.  It would be great to be able to feed it that many corenlp annotated stories.  It would also be great not to have to have a special flag for which stories we annotate, but instead just to annotate all english language stories.

Can you please generate an estimate of how many stories the corenlp annotation can handle and if that number is high enough for us to annotate all english language stories?

**Comment by pypt** [comment]
I'll temporarily stop the CoreNLP annotator workers on mcdb1 in order to do the benchmark.

**Comment by pypt** [comment]
I did some basic benchmarking of the CoreNLP processing.

With an optimal number of 16 job broker (Gearman) workers, we can annotate a single story in ~0.21 seconds. That makes it possible to annotate ~411k stories per day.

Currently counting English (or `NULL`) language stories on mcdb1 which have at least one sentence.

**Comment by hroberts** [comment]
A quick quick dashboard result says that we have about 150k stories with 
at least one english sentence per day for the last 2 weeks.

We have to be aware that we are load testing this and rahul's geotagging 
separately on the same hardware that is going to run both.  So we are 
not going to get the full throughput of either.  But it seems like we 
should easily have room to at least annotate + geotag all new english 
language stories at a minimum.

-hal

**Comment by pypt** [comment]
I forgot to mention that mcnlp only goes to around 50% of CPU usage (maybe CoreNLP is more disk-bound?), so it's possible that Rahul's service could use up the remaining 50%.

**Comment by hroberts** [comment]
Yes, some of the load is on postgres and amazon, and the load on mcnlp 
will not be totally exclusive with Rahul's work.  So I think we'll get 
better than 0.5x from each process.  But it won't be 1x either.

I think we clearly have room for the whole stream of new stories, so it 
would be safe to turn that one and get a sense for how much slack we end 
up with.  We will probably end up building a queueing daemon as we have 
in the past that just looks for slack in the pipeline and inserts 
archive stories into the queue as there is slack.


-hal

**Comment by pswheeler** [comment]
Hi Linas - out of curiosity is this purely job execution time or is it also inclusive of the time for the worker to switch jobs?

On Fri, May 20, 2016 at 12:17 PM, Linas Valiukas <notifications@github.com> wrote:
I did some basic benchmarking of the CoreNLP processing.

With an optimal number of 16 job broker (Gearman) workers, we can annotate a single story in ~0.21 seconds. That makes it possible to annotate ~411k stories per day.

Currently counting English (or NULL ) language stories on mcdb1 which have at least one sentence.

**Comment by pypt** [comment]
It's wallclock time to fetch, process and store an annotation of a story and all of its sentences in a Gearman worker, so yes, it includes worker overhead.

**Comment by pypt** [comment]
We have ~149m English language stories with at least one sentence, so annotating all of them all would take up about a year.

Closing this issue then.
