### ISSUE TITLE
copy raw_downloads back to s3

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#125]
Can you please copy the few hours of raw_downloads content back to s3?  I tried searching through t the git history for a likely looking script, but I couldn't find one.

I have switched mediawords.yml to point back to s3 and restarted the crawler, but I haven't restarted any of the processing stuff because it won't be able to read the content that was just written to postgres until we copy it to s3.

**Comment by pypt** [comment]
I forgot that it was a Bit.ly PostgreSQL -> S3 script that I was talking about. I have resurrected the script, adapted it to work with downloads, and started the copy.

Side note: we should probably update `downloads.path` to remove all the obsolete `gridfs:` / `tar:` / `/path/to/file` prefixes. That way we wouldn't need cumbersome configuration exceptions like `read_all_downloads_from_s3` and `fallback_postgresql_downloads_to_s3`.

**Comment by pypt** [comment]
> Side note: we should probably update downloads.path to remove all the obsolete gridfs: / tar: / /path/to/file prefixes.

Basically run:

```sql
UPDATE downloads
SET path = 's3:downloads/' || downloads_id

-- File (no prefix), Tar ("tar:" prefix), or GridFS ("gridfs:" prefix) downloads
WHERE path NOT LIKE 'content%'
  AND path NOT LIKE 'postgresql%'
  AND path NOT LIKE 's3%'
;
```

(Maybe some sort of a [trick](http://stackoverflow.com/a/39019890/200603) comparing `downloads.path` to all three prefixes at once would work faster here, I don't know.)

**Comment by pypt** [comment]
Copied downloads to S3, updated `downloads.path` of those copied downloads to point to S3 again, wiped `raw_downloads` table (backed it up first), restarted all processing services.
