### ISSUE TITLE
hard dependency on python 3.5?

### ISSUE THREAD

**Issue by AlJohri** [berkmancenter/mediacloud#135]
hi there, I was wondering why there is a hard dependency on python 3.5? i couldn't find any note in the documentation

**Comment by pypt** [comment]
Are you wondering why we have a dependency on Python, Python 3 or Python 3.5 specifically?

We're attempting to rewrite our codebase to Python 3, some of the utility classes and Python database handler are already in Python:

https://github.com/berkmancenter/mediacloud/tree/master/mediacloud/mediawords

I do this rewrite on Python 3.5, so to get least surprises I have hardcoded it almost everywhere. I've read that 3.6 has some major changes that I didn't look into yet, so haven't done the upgrade.

Also, Ubuntu 12.04 (which is still running on multiple of our servers) ships with Python 3.2 which is too old for our needs, e.g. doesn't have type hinting. So, simply depending on `python3` doesn't cut it.

**Comment by pypt** [comment]
Added a few sentences on 3.5 to [coding guidelines](https://github.com/berkmancenter/mediacloud/blob/master/doc/coding_guidelines.markdown).

**Comment by AlJohri** [comment]
Cool, good to know. I don't think I've seen major differences in my apps using 3.6 but I haven't used any type annotations yet so may the differences are there. Would be curious if when you get a chance you could list some of the differences you were most concerned about / wanted to test.

**Comment by pypt** [comment]
Choice of 3.5 was rather arbitrary - 3.6 was released just days ago at the time, I was using 3.5 for development, and I had to enforce a specific version on all those different environments.

I'm sure 3.6 wouldn't cause any problems, majority of Python code has rather paranoid tests, just the Inline::Python binding code might break.
