### ISSUE TITLE
having a lot of trouble getting Inline::Python to work with virtualenv

### ISSUE THREAD

**Issue by AlJohri** [berkmancenter/mediacloud#137]
hi there, I'm having a lot of trouble getting Inline::Python to work properly with virtualenv. this is partly because I'm new to perl, perlbrew, carton, etc.

ignoring `perlbrew`, `carton`, the custom fork of `Inline::Python` for a second and working with the system perl (in my case, homebrew installed perl), I'll go through an example:

#### verify perl version / installation

```
$ which perl && which cpan && which cpanm
/usr/local/bin/perl
/usr/local/bin/cpan
/usr/local/bin/cpanm
```

```
$ perl --version
This is perl 5, version 24, subversion 1 (v5.24.1) built for darwin-thread-multi-2level

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

#### verify the virtualenv mc-venv is fine and activate it

```
$ source mc-venv/bin/activate
$ which python
/Users/johria/Development/mediacloud/mc-venv/bin/python
$ pip3 freeze
appdirs==1.4.3
chardet==2.3.0
coverage==4.3.4
cssselect==1.0.1
hausastemmer==1.0
lxml==3.7.3
nose==1.3.7
packaging==16.8
psycopg2==2.7.1
pyparsing==2.2.0
python-dateutil==2.6.0
PyYAML==3.12
readability-lxml==0.6.2
six==1.10.0
url-normalize==1.3.1
```

#### uninstall and reinstall Inline and Inline::Python

```
$ cpanm --uninstall Inline Inline::Python
$ cpanm Inline
$ INLINE_PYTHON_EXECUTABLE=/Users/johria/Development/mediacloud/mc-venv/bin/python cpanm Inline::Python --verbose
```

verify in the output it says

>Configuring Inline-Python-0.52 ... Using /Users/johria/Development/mediacloud/mc-venv/bin/python

#### check python path **without** Inline::Python to see if the virtual environment libraries and site packages exist

```
$ python -c "import sys; print(sys.path)"
['', '/Users/johria/Development/mediacloud/mc-venv/lib/python36.zip', '/Users/johria/Development/mediacloud/mc-venv/lib/python3.6', '/Users/johria/Development/mediacloud/mc-venv/lib/python3.6/lib-dynload', '/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Users/johria/Development/mediacloud/mc-venv/lib/python3.6/site-packages', '/Users/johria/Development/mediacloud/mediacloud']
```

#### check python path **with** Inline::Python to see if the virtual environment libraries and site packages exist

```
$ perl -le 'use Inline Python=>q{import sys; print(sys.path)}'
['', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Users/johria/Library/Python/3.6/lib/python/site-packages', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages']
```

As you can see, the `mc-venv` folders aren't in the python path. This is the exact problem I get when trying to run `./script/start_mediacloud_server.sh`:

```
Running plackup on Carton on PID 95111 and arguments:
['', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/usr/local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/site-packages', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Users/johria/Library/Python/3.6/lib/python/site-packages', '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mediawords'
```

I additionally printed out the sys.path in the import module perl function to show that the mc-venv is not being loaded even though Inline::Python is built with it.

I'm pretty lost how to debug further. Any guidance?

**Comment by AlJohri** [comment]
I tend to use `pyenv` for my local python development. I don't think this should be relevant to the issue but for some reason, Inline::Python is not using the virtualenv or my pyenv installation, but instead straight switching to the homebrew installed python at `/usr/local/bin/python3`.

**Comment by AlJohri** [comment]
Ah, I have may have found the culprit?

```
$ INLINE_PYTHON_EXECUTABLE=/Users/johria/Development/mediacloud/mc-venv/bin/python perl Makefile.PL

Using /Users/johria/Development/mediacloud/mc-venv/bin/python
Using These Settings:
   Extra Libs:  -ldl  -framework CoreFoundation
   Python Lib:  -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m
   Includes:    -I/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/include/python3.6m
   Extra Flags: none (perl Makefile.PL --help for details)
Unrecognized argument in LIBS ignored: '-framework'
Unrecognized argument in LIBS ignored: 'CoreFoundation'
Generating a Unix-style Makefile
Writing Makefile for Inline::Python
Writing MYMETA.yml and MYMETA.json
```

Seems like the `Python Lib` is being assigned incorrectly.

**Comment by AlJohri** [comment]
Okay, I deleted the virtualenv, and then ran:

```
./install/install_python_dependencies.sh
source mc-venv/bin/activate
./install/install_modules_with_carton.sh
```

Now, it's using my pyenv installation but still not using the virtualenv:

```
Running plackup on Carton on PID 1423 and arguments:
'3.6.0 (default, Mar 23 2017, 22:29:58) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]'
['', '/Users/johria/.pyenv/versions/3.6.0/lib/python36.zip', '/Users/johria/.pyenv/versions/3.6.0/lib/python3.6', '/Users/johria/.pyenv/versions/3.6.0/lib/python3.6/lib-dynload', '/Users/johria/.pyenv/versions/3.6.0/lib/python3.6/site-packages']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mediawords'
Error while loading /Users/johria/Development/mediacloud/app.psgi: Error -- py_eval raised an exception at lib/MediaWords/Util/Python.pm line 39.
Compilation failed in require at lib/MediaWords/CommonLibs.pm line 16.
BEGIN failed--compilation aborted at lib/MediaWords/CommonLibs.pm line 16.
Compilation failed in require at lib/MediaWords.pm line 3.
BEGIN failed--compilation aborted at lib/MediaWords.pm line 3.
Compilation failed in require at /Users/johria/Development/mediacloud/app.psgi line 4.
BEGIN failed--compilation aborted at /Users/johria/Development/mediacloud/app.psgi line 4.
```

**Comment by AlJohri** [comment]
I installed the python dependencies globally (in my pyenv installation) and added this line to the top of Python.pm

```
print(py_eval("import sys; sys.path.insert(1, 'mediacloud')", 2));
```

![screen shot 2017-04-06 at 12 34 06 pm](https://cloud.githubusercontent.com/assets/2790092/24765305/591de350-1ac5-11e7-8b8b-1c0ef0c94d74.png)

**It's working now!!!!** 🙌

It'd still appreciate some help getting `Inline::Python` to respect the virtualenv. I think @pypt might be the best to answer this. Let me know when you get a chance!

**Comment by pypt** [comment]
Al, please run install.sh (or scripts called from install.sh one by one). The script:

* installs correct Python version (3.5; if you run 3.6, you might introduce 3.6-only code to the codebase while we're running 3.5);

* creates necessary .pch file in virtualenv (mc-venv/) that points to mediacloud/;

* installs Perl dependencies, complete with patched Inline::Python (I've fixed a memory leak, but opensource being opensource, the maintainer is rather slow to merge it), sets correct environment variables to be able to install OpenSSL-dependent modules, etc.

* installs system packages of correct versions which don't break under load;

* sets needed kernel parameters;

* does other stuff.

install.sh is tested daily on EC2 16.04 instance so it should work. OS X install might be less stable, we don't do it every day; I'm the one to blame for this, if you encounter problems, let me know.

It would be great to be able to install Media Cloud without all this extra "helper" scripts, but given the current circumstances (we run mainly on a programming language that virtually no one uses, we run some code in yet another programming language, we join the two with a somewhat stable binding code, and we have a single codebase that does everything - fetching stuff, extracting stuff, webserving UI, webserving API, doing researchy stuff, etc. etc.), having a single yet brittle and complex install script is the only way to do it.

If you need help installing the thing on OS X, we can have a TeamViewer session or something too, this would be a very quick way to do the whole thing. Just let me know, ready to help.

**Comment by AlJohri** [comment]
Thanks! For what it's worth I started with install.sh and made a bunch of OSX specific modifications to make it work except for this one part. I'll submit a PR after some more testing.

I would love to TeamViewer if you have some time. Do you have some time later today? I'm free after 4 pm.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pypt** [comment]
Today not really, I'm in GMT+crazy. Maybe Friday some time early in the morning? Or some time next week?

**Comment by pypt** [comment]
Okay, 9 AM ET on Friday (today) then.

**Comment by pypt** [comment]
You probably have figured it out by yourself, but the following magic lines create `.pch` file pointing to Python stuff under `mediacloud/`:

https://github.com/berkmancenter/mediacloud/blob/master/install/install_python_dependencies.sh#L53-L64

Then, when installing Inline::Python, we first activate virtualenv to make the module use the correct `python3` binary, and then point Inline::Python to virtualenv's `python3` by setting `INLINE_PYTHON_EXECUTABLE`:

https://github.com/berkmancenter/mediacloud/blob/master/install/install_modules_with_carton.sh#L49-L59

Lastly, we (re-)activate virtualenv before running every Perl script:

https://github.com/berkmancenter/mediacloud/blob/master/script/run_carton.sh#L10-L11

So, as a result, Inline::Python (Perl scripts) use correct virtualenv under `mc-env/` and see our Python code under `mediacloud/` (thanks to the `.pch` file).

**Comment by AlJohri** [comment]
@pypt I'm online on Skype at al.johri and send you an email with my teamviewer id and current password. My email is al.johri@gmail.com

**Comment by pypt** [comment]
Closing this then, seems that we have figured out everything over Skype. Please reopen if needed.
