### ISSUE TITLE
scrape stories for uk.reuters.com, spectator.co.uk, buzzfeed.com, bloombergtv.ca

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#187]
We need historical stories for these sources for 2017-01-01 to 2017-04-01.

**Comment by pypt** [comment]
At least two of the websites (Buzzfeed and Reuters UK) have extensive sitemaps that could be used for discovering and fetching articles within a given date range, e.g.:

1. Open https://www.buzzfeed.com/robots.txt
2. Look for `Sitemap:` entries
3. Open one of the sitemaps, e.g. https://www.buzzfeed.com/sitemaps/en-us/sitemap_all.xml
4. The sitemap contains a lot of sub-sitemaps sorted by date, e.g. https://www.buzzfeed.com/sitemaps/en-us/sitemap_all/2017_1.xml
5. Open the sub-sitemap, e.g. https://www.buzzfeed.com/sitemaps/en-us/sitemap_all/2017_1.xml
6. Fetch links with articles

If this is only a one-off job and Anushka needs a bunch of HTML (text) articles given to her in some form, we can write a small script to do that. If we need to integrate this with the crawler, then you're right, #45 is a bigger job that would require more testing. Also, the remaining two websites don't have such sitemaps.

**Comment by hroberts** [comment]
reuters has ~180 stories to scrape for just three months.  that scraper is running but will take a few weeks to finish.

the others are finished.  the buzzfeed and bloombergtv sources required updates to the date guessing module to correctly find dates.

**Comment by hroberts** [comment]
reuters is still working in the background, but anushka is going to run the data without reuters, so I'm marking this as done.
