### ISSUE TITLE
Remove Solr distribution from repository

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#23]
Remove Solr distribution from `solr/`, install Solr using Gradle or some other build system instead.

Most of this work is already done in [`solr_gradle` branch](https://github.com/berkmancenter/mediacloud/tree/solr_gradle), I just need to freshen up the branch a little.

I'm aware that Solr 5+ is a standalone app but I think it would still be unavoidable to install and use Solr without some sort of build system in-place, and Gradle seems like a good option.

Sub-tasks:

1. Move Solr's data to `data/solr/`.
2. Rename Solr collections from default `collection1` / `collection2` to `development` / `testing` or some other sensible name.
3. Have some thought about making Solr's sharding more sane. `cp -R`ing directories looks like something that could be improved.
6. Remove [at least ~200 MB worth of history under `solr/`](http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-a-git-repository) from repository.

**Comment by pypt** [comment]
Still working on it, just figured out a nice way to create shards with Gradle.

It looks like that we'll be able to configure the number of shards in Supervisor (so, via `mediawords.yml`).

**Comment by pypt** [comment]
After pondering around it and asking away on #solr @ Freenode, I'm starting to lean towards using "good old" shell scripts (or maybe Perl scripts that start and manage shell commands) instead of Gradle or any other build system.

The problem with a build system such as Gradle is that it's:

1. Designed to build and install stuff, not to run it. For example, it would require some more exotic code if we wanted to start Solr instance in the background and wait for the TCP port to become available to configure it.
2. Gradle is able to install Solr from Maven which feels very natural, but it only installs JARs of the package and not the accompanying tools for actually running it. All these tools do is `java -cp ... org.apache.solr.SomeClass` with some parameters being set, Gradle can do that, but then I have to replicate the tool into a Gradle build script which feels like reinventing the wheel (however crappy the initial wheel were to be)

So, I think I'll come up with a bunch of shell / Perl scripts that download Solr distribution, extract it, start ZooKeeper + Solr shards, make sure they're working, etc.

**Comment by hroberts** [comment]
Shouldn't we use ansible for this?  Seems natural for both the initial 
install and the cluster control mechanism.

It would also be a good chance for you to learn ansible on a smaller 
project before tackling our core processes.

-hal

**Comment by pypt** [comment]
I haven't finished the Ansible tutorial yet, but I think the tool is mainly used for setting up systems, keeping them at a certain desirable state and automating repetitive tasks consisting of many steps.

Not sure if Ansible would be directly applicable here. Even if it was, it shouldn't be hard to redo a shell script or two into Ansible's playbooks afterwards.

I'd say we start with basic shell scripts first and upgrade Solr itself.

**Comment by pypt** [comment]
Some breakthrough: externally-installed Solr works and passes API unit test.

Done:

* Removed Solr distribution from code repository.
* Extracted out custom configuration files from `solr/`, put both collections to `solr/mediacloud/collections/`.
	* As they're identical, the configuration is kept in `_base_collection/`, and `collection[12]` are symlinks to it.
* Added support for running external ZooKeeper instance as [recommended by the documentation](https://cwiki.apache.org/confluence/display/solr/Setting+Up+an+External+ZooKeeper+Ensemble).
* Developed a fancy yet straightforward [Python module](https://github.com/berkmancenter/mediacloud/tree/solr_install_externally/solr/mc_solr) which is able to install, set up and run both Solr and ZooKeeper:
	* Fetches Solr and ZooKeeper distributions from Apache's archive and extracts them to `dist/`.
	* Creates a tree of symlinks under each Solr instance's `solr.home` instead of `cp -R`ing the whole Solr distribution.
	* Port numbers, JVM arguments, etc. are [configurable too](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/solr/mc_solr/constants.py).
* Added utility scripts that use said module:
	* [`run_solr_standalone.py`](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/solr/run_solr_standalone.py) - runs standalone Solr instance (e.g. for developing and testing). Writes data to `data/solr/mediacloud-standalone/`.
	* [`run_zookeeper.py`](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/solr/run_zookeeper.py) - starts a ZooKeeper instance and bootstraps it with Solr's config. Writes data to `data/solr-zookeeper/`.
	* [`run_solr_shard.py`](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/solr/run_solr_shard.py) - sets up and starts a single Solr shard that connects to an external ZooKeeper instance started previously (the idea is that each shard will be started and managed independently via Supervisor). Writes data to `data/solr/mediacloud-shard-\d/`.
	* [`update_zookeeper_config.py`](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/solr/update_zookeeper_config.py) - updates Solr configuration on ZooKeeper instance (doesn't reload the shards though).
	* [`reload_solr_shards.py`](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/solr/reload_solr_shards.py) - reloads Solr shards after ZooKeeper configuration changes.
	* Helper scripts support various other parameters to customize the Solr deployment further (try `-h`).
* Made Solr store its standalone instance / shard data under `data/solr/`, like we do with the rest of Media Cloud's data.
* Both Solr and ZooKeeper now log everything to `STDOUT/STDERR` for us to be able to maintain all the logs in one place using Supervisor.
* Solr's configuration on ZooKeeper gets updated every time ZooKeeper is (re)started.
* Various locks and paranoia all around to prevent someone from screwing up the setup by passing wrong parameters, etc.

Example:

    # Start ZooKeeper, bootstrap with configuration under `solr/mediacloud/`
    ./solr/run_zookeeper.py
    
    # Start two shards
    ./solr/run_solr_shard.py -n 1 -c 2
    ./solr/run_solr_shard.py -n 2 -c 2

To-do:

* Make Solr Python wrapper script kill Solr itself (right now only Ctrl+C works for whatever reason, `kill -TERM` doesn't).
* Rename `collection1` / `collection2` to `production` / `development` (Or is it vice versa? That's exactly the reason.)
* Add script to migrate old Solr data layout to `data/solr/`.
* Set up Supervisor to start and manage ZooKeeper and Solr shards.
* (Maybe?) improve shard naming by setting [`coreNodeName` / `shard` in `core.properties`](https://cwiki.apache.org/confluence/display/solr/Defining+core.properties) (in what way though?).
* Write some basic docs.
* Remove Solr binary distribution [from Git history](http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-a-git-repository).

**Comment by hroberts** [comment]
This looks terrific, Linas.

Very excited to sanitize our solr install and especially to get running 
on solr 6.

I don't see in the below any equivalent to the start-solr-shards.pl or 
create-solr-shards.pl scripts.  How do those fit into the new setup?

-hal

>   * Rename |collection1| / |collection2| to |production| / |development|
>     (Or is it vice versa? That's exactly the reason.)

The idea of the two collections is not production and development but 
production and staging, so that we can do a full import into the staging 
server and just swap the collections to get the new data into production 
with trivial downtime.  Solr.pm queries the database_variables table in 
postgres every time it queries solr to find out which of the two 
collections is production.

Happy to do this entirely in solr by just swapping in a new collection. 
But when I set this up initially, I couldn't figure out any way in solr 
to programmatically change collection names.  There are some core 
creation / naming api end points, but my memory is that they were flaky 
and that it was not clear what they were actually doing.

Also, in practice, I have tested by never actually done a staged 
reimport.  Our imports are much faster now, so the easiest thing to do 
is just to put all stories into solr_extra_import_stories and wait a few 
weeks for everything to get reprocessed.  Without our success using 
rsync as a backup mechanism, an alternative method that doesn't require 
any mucking with the solr setup or connections is just to fire up some 
ec2 machines for the import, run it, then rsync the new data back to our 
servers.  So we might just get rid of all the code supporting the two 
collections altogether.

-hal

**Comment by pypt** [comment]
> Very excited to sanitize our solr install and especially to get running
> on solr 6.

To be clear, this setup is still running Solr 4.6. I'm about to upgrade to Solr 5 and then to 6 later on  as part of #24.

As per your advice, I have taken into account that starting and running Solr has changed since version 5, but it hasn't gotten that much easier, so I don't expect that the Python module that I just wrote would become obsolete by an improved setup process (because it hasn't improved by that much).

> I don't see in the below any equivalent to the start-solr-shards.pl or
> create-solr-shards.pl scripts.  How do those fit into the new setup?

`run_solr_shard.py` (creates if needed and) starts a Solr shard, e.g. `run_solr_shard.py -n 1 -c 2` would start shard 1 out of 2 (creating it first if necessary).

I wasn't sure about which shorthand parameter names would be the most intuitive for `shard_num` and `shard_count` (current ones are `n` and `c` respectively). Would `m` and `n` do better?

> So we might just get rid of all the code supporting the two
> collections altogether.

Will happily do that! Should I kill the Perl collection swapping code too?

**Comment by hroberts** [comment]
> |run_solr_shard.py| (creates if needed and) starts a Solr shard, e.g.
> |run_solr_shard.py -n 1 -c 2| would start shard 1 out of 2 (creating it
> first if necessary).

great.

> I wasn't sure about which shorthand parameter names would be the most
> intuitive for |shard_num| and |shard_count| (current ones are |n| and
> |c| respectively). Would |m| and |n| do better?

I n and c are fine.

> Will happily do that! Should I kill the Perl collection swapping code too?

Yes, I think so, based on me not having used it in the 2+ years since I 
wrote it.

 From a resource point of view, I think it's a lot smarter to just 
create the index somewhere else and copy it into place.

-hal

**Comment by pypt** [comment]
`solr_install_externally` branch is finished, tested back and forth, ready for deploying. Will try to run it on `mcquery*` tomorrow.

Summary:

* Solr removed from code repository; instead, helper scripts install a specified version of Solr themselves when needed.
* All Solr (standalone and shard) data moved to `data/solr/`.
* Concept of "creating" shards is gone; you just start the helper script with correct parameters and trust it to create the necessary directory / symlink structure for every shard.
* ZooKeeper and Solr shards are now being run separately, no more "leader" shard (external ZooKeeper instance figures out shard hierarchy if necessary).
* ZooKeeper updates Solr configuration on every start up.
* `collection1` and `collection2` are symlinks to `_base_collection` to avoid duplicating the same thing.
* Solr shards and accompanying ZooKeeper are now Supervisor services.
* Solr shard ports start with 7981; 8983 is used solely for the development standalone Solr instance.
* Solr shards and ZooKeeper are now [configured in `mediawords.yml`](https://github.com/berkmancenter/mediacloud/blob/solr_install_externally/mediawords.yml.dist#L145-L177).
* Helper scripts try to shutdown ZooKeeper and Solr shards gracefully for one minute, then give up and `SIGKILL` them.

Out of scope of this task:

* Removing `collection2`.
* Removing megabytes of Solr binaries from Git repo.
* Upgrading Solr to version 5 / 6.
* Moving Solr's Media Cloud configuration to a separate repository (makes sense with our idea of horizontal scaling, [custom sysctl properties](https://github.com/berkmancenter/mediacloud/blob/master/doc/hosting/solr-hosting.markdown#mit-specific-instructions), the fact that Solr instances are being run on completely different servers than Media Cloud core itself, and general code scoping).

**Comment by hroberts** [comment]
good work!

obviously would be a good idea to run a solr backup on faith before 
doing the upgrade.  if you need me to do that, just ping me on slack.

-hal

**Comment by pypt** [comment]
Trying to run backup on Faith before deploying Solr updates.

I don't have permission to write to `/space01/mediacloud_pgsql_backup/solr` again (you should probably [set sticky bit](http://unix.stackexchange.com/a/1315) on directory or just give me root access), so I `cp -R`ed `solr` directory to `solr-linas`, modified `backup-solr.sh` accordingly and started backing up to my own directory.

Unfortunately, rsync somehow decided that most (all?) of the files between `solr-linas/mcquery*/` and actual servers are different and so is pretty much fetching everything from mcquery*. It's strange that it's doing that because `cp` preserved modification dates, but whatever.

I'll leave it running for a while. Meanwhile, Solr story imports on mcquery2 remain disabled.

**Comment by pypt** [comment]
Deployed 4.6.0 on mcquery*, closing then. Working towards 6.1.0 upgrade (#24).
