### ISSUE TITLE
Adding new sources with unicode urls

### ISSUE THREAD

**Issue by ColCarroll** [berkmancenter/mediacloud#237]
Using the [Python client](https://github.com/mitmedialab/MediaCloud-API-Client) on a valid URL triggers a 500 error:

```
import mediacloud

admin = mediacloud.api.AdminMediaCloud(API_KEY)
admin.mediaCreate([{
    'name': 'Deutsche Welle (Dargwa)',
    'tags_ids': [],
    'url': 'http://www.dw.com/fa-af/دويچه-وله-دری/s-10259'
}])
```
A copy of the stack is [here](https://gist.github.com/ColCarroll/23119826646f46566209383db1515518)

It seems like it must be the unicode url, but I cannot recreate this using just this project:
- `UserAgent().get(url)` does fine
- `UserAgent().parallel_get([url])` does fine
- Triggering the equivalent of both in perl does fine

**Comment by pypt** [comment]
Did you try this just now or some time before?

**Comment by ColCarroll** [comment]
Just now.  There was a similar unicode error a week or two ago that I assumed was transient, but I no longer have that stack trace.

**Comment by pypt** [comment]
Thanks, working on a fix.

**Comment by pypt** [comment]
Fixed, deployed, should work now. FYI, I've already imported `http://www.dw.com/fa-af/دويچه-وله-دری/s-10259` media URL as a test.
