### ISSUE TITLE
db_migrations out of date?

### ISSUE THREAD

**Issue by ColCarroll** [berkmancenter/mediacloud#266]
It looks like the `db_migrations` documentation is at least moderately out of date, in its references to subversion.

**Comment by hroberts** [comment]
fixed.  new file is intended to be a simple and clear as possible.  please let me know if it is not.

**Comment by hroberts** [comment]
I think I messed up the initial commit, but it is committed and pushed to master now.

**Comment by ColCarroll** [comment]
Looks great, thank you!
