### ISSUE TITLE
error creating topic with max_stories parameter 

### ISSUE THREAD

**Issue by cindyloo** [berkmancenter/mediacloud#282]
MCException: Error - got a HTTP status code of 500 with the message "Internal Server Error", body: {"error":"Error(s): Caught exception in MediaWords::Controller::Api::V2::Topics->create \"Modification of non-creatable hash value attempted, subscript \"max_stories\" at lib/MediaWords/Controller/Api/V2/Topics.pm line 253, <$fh> line 1

**Comment by pypt** [comment]
Cindy, can't reproduce. Could you post an API call that you've made?

**Comment by cindyloo** [comment]
I can't reproduce either - I was just able to create a query with max_stories set. Either I was testing in the wrong branch w an old version of the api
