### ISSUE TITLE
Recover locked out RabbitMQ message queue

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#32]
After restarting services on mcdb1 today, RabbitMQ decided that it didn't shutdown cleanly the last time so it needs to recreate the message index. However, the recreation process seems to run indefinitely, use up all the memory and either stall or crash with OOM errors. The locked out queues mostly consist of reextraction Bit.ly fetch jobs.

I have tried to copy 87 GB worth of RabbitMQ Mnesia database to mcquery3 and restore the index using all the available RAM and an idle machine, but that didn't work. Did [some more complaining](https://groups.google.com/d/msg/rabbitmq-users/EJ7Z40oK_bM/VZMo-0_RBwAJ) on `rabbitmq-users` mailing list, will see how it goes. There are funky ways to use Mnesia database directly to extract a list of messages, but I don't want to go into that just yet.

mcdb1 currently runs an empty RabbitMQ instance, all the messages are being processed pretty quickly, so the queues shouldn't grow big and reindexing won't cause problems. Also, I made Supervisor wait for RabbitMQ to shutdown a little bit longer with the hope that the server will manage to stop gracefully (6fec2b7).

**Comment by hroberts** [comment]
The response seems to be to upgrade erlang.  I thought the answer last 
time was to downgrade erlang.  Hrmph.

-hal

**Comment by pypt** [comment]
Just tried to both upgrade and downgrade Erlang - no effect. Will try to start RabbitMQ on Ubuntu 16.04 (and prepare MC code for Ubuntu 16 in the process), maybe that will change something.

I think they're reluctant to admit that their (re)indexing implementation is just not that great at the moment. Here's the [issue created by the same guy](https://github.com/rabbitmq/rabbitmq-server/issues/838) about a disk-based message index store plugin that they're about to start working on.

Some more ideas:

* Docs mention that there are [alternative message index implementations](https://www.rabbitmq.com/persistence-conf.html#alternate-index) however I can't seem to find them.
* Don't let a single RabbitMQ instance grow that big by round-robining messages between multiple smaller instances (in a cluster)?

As for the short-term solution, I think I'm going to simply grep the messages from the database and re-add them to the queue.

**Comment by pypt** [comment]
Recreating index on Ubuntu 16.04 didn't work either.

I have extracted a list of jobs that were in the queues to a bunch of text files. Leaving `data/rabbitmq-old_unindexed_queue/` directory in place for now in case someone on *rabbitmq-users* comes up with an idea of how to restore it.

If not, I'll probably go look into clustering RabbitMQ servers or plugging in custom index implementation.

**Comment by pypt** [comment]
Upon developer's request, posted [the whole 89 GB dump to S3](https://groups.google.com/d/msg/rabbitmq-users/EJ7Z40oK_bM/9oO_XWgWCAAJ). Hope he'll find some time to look into it.

**Comment by pypt** [comment]
Tried to ping the developer who was keen to help:

<img width="309" alt="screenshot 2016-07-08 04 54 42" src="https://cloud.githubusercontent.com/assets/181949/16675256/21af504e-44c8-11e6-9259-16b094465270.png">

Decided it would be faster to just recreate the queue and try to keep it small until we figure out how to mitigate the index rebuilding problem.

So, fetched a list of stories without Readability tag to `stories_without_readability_tag` table and started to gradually add them to the reextraction queue in order to test extractor's `story_sentences` query improvements (#28).

About to re-add failed Bit.ly queue to `bitly_processing_schedule` too.

**Comment by pypt** [comment]
Started adding 25m failed Bit.ly fetch jobs to `stories_from_failed_bitly_rabbitmq_queue` table, will reschedule them for Bit.ly processing later on.

**Comment by hroberts** [comment]
for whom does the developer work?

can we pay him or his employer in some way to fix the problem?

-hal


On 7/7/16 8:58 PM, Linas Valiukas wrote:
> Tried to ping the developer who was keen to help:
>
> screenshot 2016-07-08 04 54 42
> <https://cloud.githubusercontent.com/assets/181949/16675256/21af504e-44c8-11e6-9259-16b094465270.png>
>
> Decided it would be faster to just recreate the queue and try to keep it
> small until we figure out how to mitigate the index rebuilding problem.
>
> So, fetched a list of stories without Readability tag to
> |stories_without_readability_tag| table and started to gradually add
> them to the reextraction queue in order to test extractor's
> |story_sentences| query improvements (#28
> <https://github.com/berkmancenter/mediacloud/issues/28>).
>
> About to re-add failed Bit.ly queue to |bitly_processing_schedule| too.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/berkmancenter/mediacloud/issues/32#issuecomment-231257174>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABvvTwas2mCMK81zIZRRp7IDSVNlavMMks5qTa6sgaJpZM4I_rlS>.
>

-- 
Hal Roberts
Fellow
Berkman Center for Internet & Society
Harvard University

**Comment by pypt** [comment]
Pivotal, which offers [commercial support](https://www.rabbitmq.com/services.html). Not sure about the price though.

**Comment by pypt** [comment]
Currently copying failed Bit.ly jobs from `stories_from_failed_bitly_rabbitmq_queue` temporary table to Bit.ly processing schedule. Will commit some fixes to how jobs are being scheduled and restart Bit.ly fetchers afterwards.

**Comment by pypt** [comment]
Restored the old queue, also remade [`process_bitly_schedule.pl`](https://github.com/berkmancenter/mediacloud/blob/master/script/process_bitly_schedule.pl) into a polling Supervisor daemon (instead of a Cron script) which fetches a chunk of due (=3 or 30 days old) stories to add to Bit.ly fetch queue and then waits for 10 seconds in order to not fill up RabbitMQ's queue too much (so that I don't have to grep and restore those stories again).

Due to reextraction hiccups and RabbitMQ's downtime, currently there are 28,634,000 unique stories to be processed, i.e. for which it's time to fetch Bit.ly stats. At the current rate of ~20 stories/s, the Bit.ly processing queue should be able to catch up in 17 days.
