### ISSUE TITLE
Replace db_row_last_updated triggers with polling scripts that feed solr_import_extra_stories

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#36]
We have complex triggers in the database that update story_sentences.db_row_last_updated whenever
a row in stories or stories_tags_map is updated.  The Solr::Dump just queries story_sentences to
find all sentences that have updated since the last import.

We don't do this with changes to media_tags_map because the necessary triggers would at times take
hours to run (for instance, adding a tag to the nyt).  So for media_tags_map we just run a polling script
that checks for recently updated media sources and insert all stories belonging to those stories
into solr_import_extra_stories.  The import script takes up to 150k stories at a time from that table 
during each import to gradually incorporate those changes.

I think we use this model for all updates to stories and stories_tags_map, so that updating those tables
does not trigger expensive and lock hogging queries to update lots and lots of rows in story_sentences.  Story and story tag updates would be much quicker, and I think we would reduce our deadlock issues as well.

The only downside I can think of is that story and story tags updates may take a little while to catch up through the queue.  But in practice we would just be replacing the updates that happen now through the triggered ss.db_row_last_updated updates.  In theory we could build priorities into the queue so that story and story tag updates do not get displaced by media or other large reprocessing queues.

**Comment by pypt** [comment]
I agree, having a single table listing stories that need to be (re)imported sounds like a very straightforward approach.

I'd rename `solr_import_extra_stories` to `solr_import_stories` too because there wouldn't be anything "extra" about it anymore.

**Comment by hroberts** [comment]
this should be done as part of the story indexing.
