### ISSUE TITLE
add universal http request logging and blacklist

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#46]
elvocero.com has strongly complained to us for a second time for hitting their site too hard.  The first time was from running the feedly backfill and not having enough per-media throttling in the crawler.  We fixed that, but we hit them with about 3500 requests in two hours on thursday, but I don't find any of the requests they are complaining about in the downloads table or in the topic_mine:* logs.

I spent a couple of hours pouring through the code to try to figure out how we could be generating those requests without leaving a trace in downloads or the spider logs, and I could never puzzle it out.

So I have added a universal http request log that will print every request through code that uses MediaWords::Util::Web::UserAgent, which is virtually every request we generate.  The requests get appended to data/mediacloud/http_request.log.

I also added code to invalidate requests that match the mediawords.yml->mediawords->blacklist_url_pattern regex and added 'elvocero.com' as the initial blacklist pattern.  This should both prevent any of our code from requesting a page from elvocero.com and will print out a stacktrace when any such request is attempted so that we can track down where it is coming from.

Instead of writing the single file, I should write a different file for each day so that we can easily rotate them out after a week or so.  I'll do that before closing this issue.

**Comment by pypt** [comment]
Thanks for letting me know.

IMHO additionally you could have:

* Described all those reasons in the commit message or code comments because after some time it will be impossible to backtrack the relevant code to this issue. *"log all http requests"* is not too useful in figuring out why they are logged. Alternatively, you could have added "refs #46" in the commit message to point to this issue on GitHub.
* Added a unit test that at least makes sure that the ignored site actually gets ignored.
* Used Log4perl (e.g. a custom handler for `::Web`) for logging those requests because it's easier to reroute it and there are recipes for adding logrotate for Log4perl.
* Put the change in a separate branch first.

**Comment by pypt** [comment]
Here's the sample outcome of no unit testing:

<img width="1422" alt="screenshot 2016-08-08 16 15 42" src="https://cloud.githubusercontent.com/assets/181949/17481011/72b8b02e-5d83-11e6-9f6c-827a8f13e529.png">

**Comment by hroberts** [comment]
That's not really a unit testable thing.  It was caused by the apache 
user not having permission to write the file created by the mediacloud 
user.   Fixed the permissions on mcdb1 and have edited the code to make 
sure group permissions are set correctly.

-hal

**Comment by pypt** [comment]
Reverted HTTP request log in 246ce1b. Problems:

* CoreNLP clients can't write to it.
* [API test on Travis can't write to it](https://travis-ci.org/berkmancenter/mediacloud/builds/150911612#L2831).
* Every chmod resets the file permissions to 400 (I think).

**Comment by pypt** [comment]
Super-quick and side effect-free solution would be to add `DEBUG("Requesting $url")` to Web.pm and later grep those debugging prints from `data/supervisor_logs/` (complete with timestamps and processes that initiated the request).

**Comment by hroberts** [comment]
The main point of this logging is to provide a single place to look for 
request logs, from which we can make a positive or negative finding with 
a high degree of certainty.

If we do the log4perl thing, we would lose entries for most jobs outside 
of supervisor, including requests initiated by cron jobs, web scripts, 
or command line scripts.

We could in theory accomplish a unified request log by using the 
log4perl.conf file.  But that requires us to get the correct 
log4perl.conf on all computers and adds lots of complexity to what 
should be a simple file write.  And would have most likely triggered the 
same permissions errors we're having with my current approach.

This is not a theoretical use case.  I only put the log into place in 
the first place because the expected ways of learning about a set of 
downloads (the downloads table or the topic_mine:* logs) were not 
showing the requests that we got complaints about.  I want to be as sure 
as possible that we there is one single place that logs every url we hit 
rather than having to wonder if the hits might be getting logged 
somewhere else or not at all because of some combination of script 
execution and log4perl configuration.


-hal

**Comment by hroberts** [comment]
closing this.  http logging and blacklisting are in place and working as expected.

mystery solved for the elvocero.com requests.  they were being looked up by the bitly stats fetcher to get url variants.  need to add throttling to that system so that we don't slam folks.
