### ISSUE TITLE
Default password?

### ISSUE THREAD

**Issue by QasimQureshi** [berkmancenter/mediacloud#492]
What would the default username/password be, after getting MediaCloud up and running on Vagrant (virtualbox)
![image](https://user-images.githubusercontent.com/3591082/46593913-0717ef80-cae9-11e8-9e25-73185ba86069.png)

**Comment by pypt** [comment]
Hey Qasim,

Try logging in with `vagrant ssh` instead. Learn more about SSHing into Vagrant instances [in the tutorial](https://www.vagrantup.com/intro/getting-started/up.html).

Please don't hesitate to reopen this issue if something still doesn't work.
