### ISSUE TITLE
Search by article source id? Search by article category?

### ISSUE THREAD

**Issue by AlJohri** [berkmancenter/mediacloud#5]
Is there an easy way to record an article's source specific ID when crawling for articles?

I'm currently using the NYT API to search for Op Ed articles and they provide ids for each article. I was hoping to find a systematic way to find the same articles in the mediacloud database but haven't had much luck.

Query: http://api.nytimes.com/svc/search/v2/articlesearch.json?fq=news_desk:(%22Editorial%22)

```json
{
    "web_url": "http://www.nytimes.com/2015/02/21/opinion/patrick-chappatte-greek-tragedy.html",
    "snippet": "Germany rejected Greece’s request for a loan extension.",
    "lead_paragraph": "Germany rejected Greece’s request for a loan extension.",
    "pub_date": "2015-02-21T11:30:00Z",
    "document_type": "article",
    "news_desk": "Editorial",
    "section_name": "Opinion",
    "type_of_material": "Op-Ed",
    "_id": "54e71f9c79881005b672947e",
    "word_count: 8
}
```

-----------------

Otherwise, is there a way to search mediacloud by an article's category? I found the c4fcm/oped-gender-report repository which uses regular expressions to extract the section. This would be good enough if I could re-index solr and include a new searchable field in the schema?

https://github.com/c4fcm/oped-gender-report/blob/master/data_acquisition/base_meta.py#L131

Please let me know what I can do. Thanks!

**Comment by hroberts** [comment]
We don't record source specific tags or ids in our database, so I think 
there's no way to do this.

-hal

On 2/22/15 5:55 AM, Al Johri wrote:
> Is there an easy way to record an article's source specific ID when
> crawling for articles?
>
> I'm currently using the NYT API to search for Op Ed articles and they
> provide ids for each article. I was hoping to find a systematic way to
> find the same articles in the mediacloud database but haven't had much luck.
>
> Query:
> http://api.nytimes.com/svc/search/v2/articlesearch.json?fq=news_desk:(%22Editorial%22)
>
> {
>      "web_url":"http://www.nytimes.com/2015/02/21/opinion/patrick-chappatte-greek-tragedy.html",
>      "snippet":"Germany rejected Greece’s request for a loan extension.",
>      "lead_paragraph":"Germany rejected Greece’s request for a loan extension.",
>      "pub_date":"2015-02-21T11:30:00Z",
>      "document_type":"article",
>      "news_desk":"Editorial",
>      "section_name":"Opinion",
>      "type_of_material":"Op-Ed",
>      "_id":"54e71f9c79881005b672947e",
>      "word_count: 8
> }
>
> ------------------------------------------------------------------------
>
> Otherwise, is there a way to search mediacloud by an article's category?
> I found the c4fcm/oped-gender-report repository which uses regular
> expressions to extract the section. This would be good enough if I could
> re-index solr and include a new searchable field in the schema?
>
> https://github.com/c4fcm/oped-gender-report/blob/master/data_acquisition/base_meta.py#L131
>
> Please let me know what I can do. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/berkmancenter/mediacloud/issues/5>.
>

-- 
Hal Roberts
Fellow
Berkman Center for Internet & Society
Harvard University
