### ISSUE TITLE
Installation Steps not working

### ISSUE THREAD

**Issue by albarki** [berkmancenter/mediacloud#541]
Hi, 

I followed the exact steps found [here](https://github.com/berkmancenter/mediacloud/blob/master/INSTALL.markdown), after i run the `./install.sh` then run the `./script/run_dev_server.sh` then access to the http://IPADDRESS:3000 i found the following errors 

```
[error] Caught exception in MediaWords::Controller::Root->default "API endpoint was not found at /mediacloud/script/..//lib/MediaWords/Controller/Root.pm line 22."
[error] Caught exception in MediaWords::Controller::Root->default "API endpoint was not found at /mediacloud/script/..//lib/MediaWords/Controller/Root.pm line 22."
```
![screenshot from 2019-01-25 02-40-08](https://user-images.githubusercontent.com/8536153/51717706-95899000-204a-11e9-9a51-2b8cdcf3925f.png)

Thanks for your support 
any help are much appreciated.

**Comment by pypt** [comment]
Hey Ibrahim Mohamed!

Thank you for your interest in Media Cloud!

We recently got rid of our deprecated web UI and left only the webapp controllers which serve the API calls available, so confusingly enough, this is that you should be getting by opening `/` path as it doesn't point anywhere anymore.

Try opening `http://your_ip:3000/status`. If it says `Works!`, you can assume that you've got Media Cloud up and running!

**Comment by pypt** [comment]
Don't hesitate to reopen the issue if you encounter any other problems or have any further questions.

**Comment by ruimgbarros** [comment]
Hi! I was having the same problem. I've opened `http://your_ip:3000/status` and it says `Works!`.
But how should I log in? `http://your_ip:3000/login` gets me the same error.

**Comment by frknasir** [comment]
> Hi! I was having the same problem. I've opened `http://your_ip:3000/status` and it says `Works!`.
> But how should I log in? `http://your_ip:3000/login` gets me the same error.

"they recently got rid of their deprecated web UI and left only the webapp controllers which serve the API calls available"
