### ISSUE TITLE
separate crawler engine and fetcher

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#564]
update the crawler to use tcp sockets so that we can run fetchers on separate machines.

**Comment by hroberts** [comment]
I am knocking this up in priority because the crawler provider process has started seg faulting.  Rather than dig through the mess to find what's triggering the perl segfault, I am going to rewrite the crawler provider in python and rewrite the crawler fetchers as proper rabbbit jobs.

The basic idea is that the provider will run as a polling process periodically checking the size of the rabbitmq crawler_fetcher queue.  Whenever the queue drops below some number (will start around ~1000), it will run the various queries that it already runs to find new things to download.  Instead of handing those downloads directly to the fetchers, it will shove them into the rabbitmq queue.  This will allow us to do a reasonable job of intelligent per-media throttling (which we can't do if we throw everything into the queue at once) while getting rid of the ugly socket based stuff altogether.  It will also speed up the crawler a good bit, since with the current setup the fetchers are idling about a third of the time just waiting for the provider to run the big query that returns the pending downloads.

This should be a pretty easy lift.  The great majority of the interesting code in Provider.pm is just carefully crafted sql queries, and I have reduced the size of that module a lot while refactoring it over the past month.  So the pythyon translation should be pretty straighforward.

**Comment by hroberts** [comment]
This is done.

The provider is now implemented in python here: https://github.com/berkmancenter/mediacloud/blob/master/mediacloud/mediawords/crawler/provider.py

Lots of simplification and optimization of the provider.  It now just does three things:
* every QUEUE_INTERVAL seconds, call provide_download_ids to get one downloads_id per host from downloads_pending, and for those downloads change the state of each to fetching and insert them into qeued_downloads;
* every STALE_FEED_CHECK_INTERVAL seconds, check for any feeds that need to be downloaded and add them to downloads_pending;
* every STALE_DOWNLOAD_INTERVAL seconds, check for any downloads stuck in fetching state for more than STALE_DOWNLOAD_INTERVAL seconds and move them back to pending for eventual requeueing.

The fetching code is still implemented in Engine.pm here:
https://github.com/berkmancenter/mediacloud/blob/master/lib/MediaWords/Crawler/Engine.pm

Lots of simplification here as well.  I removed all of the sockets stuff and replaced it with code in the existing run_fetcher() function to query queued_downloads to pop a single downloads_id off the table, sorted by queued_downloads_id asc.  After fiddling, I implemented a pop_queued_download() function to do this using a for update skip locked select, which seems to do a really nice job of handling locking for the table.

Other than the interaction with queued_downloads (which replaces the forking / sockets code that had been there), the fetching / handling code all remains the same.

I had to struggle with sql locking and optimization to get everything running smoothly:
* I use the pop_queued_download() plpgpsql function to encapsulate the select / delete into a transaction that can't be left open and to take advantage of the for update skip locked postgres feature;
* I set the autovacuum settings for downloads_pending to autovacuum every 1000000 updates so that the table does not get too bloated for the 'select distinct on (host) downloads_id from downloads_pending...' query that is the core engine of the provider;
* I managed to hang the entire postgres system by trying to add 'where downloads_id not in (select downlolads_id from queued_downloads)' to the select distinct on (host) query above.  Instead, I just set each download to fetching before I stick it into queued_downloads so that the provide_downloads query does not repeatedly provide the same downloads.
* I tried using the same database handle for the life of the crawler_fetcher, but I was running into endless deadlocks blocked by 'idle in transaction' connections; once I changed back to reconnecting to the database for each fetch, the deadlocks all went away.

Finally, I added unit tests for provider.py and for Engine::run_fetcher() and removed the horrible old test_crawler.t.  We should now have unit tests to cover all of the provider, fetcher, and handler work, and the very old test_crawler.t integration test was more trouble and test time than it was worth.

**Comment by pypt** [comment]
Congrats, great change IMHO!
