### ISSUE TITLE
Finish up partitioning "download_texts"

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#566]
After #514, we now need to finish up partitioning `download_texts`.

Currently, we have a single huge non-partitioned `download_texts_np` which is no longer gets written to, and `download_texts_p` partitioned setup where all of the new rows go to.

So, we need to:

* [x] Address `download_texts` entries with referenced downloads with `type = 'content'` and `state = 'error'` as they're weird extraction errors which shouldn't be there
* [x] Consider the order in which partitions get created
* [x] Fix up migration script for it to update the partition creation function so that it creates necessary indexes
* [x] Add native foreign key from `download_texts` partitions to `downloads_success_content` partitions
* [x] Move rows from non-partitioned `download_texts_np` to `download_texts_p` partitioned layout.
* [x] Remove INT - BIGINT "hacks", e.g. eab899f
* [x] Clean up intermediary views and such.

**Comment by hroberts** [comment]
I think this is suffering from the same int / bigint issue.  trying to query download_texts using download_texts_id results in a seq scan of download_texts_np.  I just added a work around to some code that was causing this by avoiding looking up by download_texts_id, but it would obv be better not to leave the hand grenade there.

**Comment by pypt** [comment]
* Added foreign keys from `download_texts` partitions to `downloads_success_content` partitions.
* Added a plpgsql function + Python script to gradually copy chunks of rows from non-partitioned `download_texts` to the partitioned one.
* Started the script as a Supervisor daemon on mccore1.

It's hard to say how long will it take for the move to complete. If it continued at the current rate (which it absolutely won't), the rows would get partitioned in ~5 hours. I'll let it run during the weekend and make a progress report afterwards.

Also, I had to take care of some discrepancies with `download_texts`:

* There were quite a few (3,9m rows, 31 GB) `download_texts` rows with `downloads_id` that was pointing to a non-existent row in `downloads`. Given that there was no way to restore those rows in `downloads`, I've dumped said rows and uploaded them to our "obsolete data" Glacier-backed-S3 bucket.
* There might be a bunch of rows which point to `downloads` with `state != 'success'`, e.g. at some point we were storing download / extraction errors in `download_texts` for some reason (I think it was my bug). I honestly forgot whether I've deleted those rows, so if row migration script crashes due to such broken foreign keys, I'll make the migration script skip such rows.

**Comment by pypt** [comment]
Copy ~50% complete.

**Comment by pypt** [comment]
All done:

* Rows moved
* Intermediary views removed
* Extra INT-BIGINT indices dropped
* Workarounds such as eab899f reverted
* Did a quick PostgreSQL 10.2 -> 10.5 minor version upgrade too

Next up in the partitioning saga:

* `stories` table - 64% primary key fill, 1268 GB; would get split up nicely with respect to how the rest of the tables are already partitioned using `stories_id`
* `nytlabels_annotations` and `cliff_annotations` - 0% primary key fill but those tables are huge (182 GB and 501 GB); I figure it would be cheaper to store those raw JSON annotations on S3

**Comment by pypt** [comment]
Yep, there are 209 (!) mentions of `stories_id` in `mediawords.sql`, and we'll have to make all of them into `BIGINT` :(

**Comment by pypt** [comment]
Now when I think of it, it would probably be easier to:

1. Add an empty `stories_id_bigint` column to every table
2. Take our time to fill the `stories_id_bigint` column with `stories_id::BIGINT`
3. Once `stories_id_bigint` is ready for its primetime, drop `stories_id`, rename `stories_id_bigint` to `stories_id`, make it into a primary key, and update a plethora of functions and whatnot which consider `stories_id` an `INT`
4. Now that `stories_id` is a `BIGINT`, continue with a regular program of partitioning the table

Most of the issues that we've had with queries against a partitioned `downloads` was due to a discrepancy between `INT` and `BIGINT` primary keys, so this prep work would save us from having to apply nasty hacks to a bunch of SQL queries everywhere.
