### ISSUE TITLE
GSoC 2019 ideas

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#568]
Student application period has just started, so it's about time for us to come up with some GSoC ideas.

We can reuse some from the [last year](https://cyber.harvard.edu/gsoc/MediaCloud):

* **Build a tool to do some cool visualizations**
* **Create PostgreSQL-based job queue**
    * Probably too hard and not going to happen, but it doesn't hurt to leave it there. Or should we just remove it?
* **Implement a method to detect subtopics of a topic**
    * A lot of students are asking about this idea but I'm not sure if I'm the one who would be able to be the best mentor for this task as (simply put) I don't know much about the subject. Dongge, our GSoC 2017 student, did implement subtopics using Louvain but it's still unmerged to this day.
* **Do your own freehand project**

I'd also add easier, low-priority tasks from our side-projects, e.g. the [Ultimate Sitemap Parser](https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser/issues):

* *(easy)* [Add support for RSS / Atom sitemaps](https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser/issues/3)
* *(easy)* [Detection of sitemap if it's not present in robots.txt](https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser/issues/8) (has some relevant discussion and stats too; I wonder whether Alex (@kienli) is a student!)
* *(medium-hard)* [`yield` found links instead of `return`ing them](https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser/issues/2) (simple concept but would probably require rethinking and rewriting a lot of stuff)

[`sentence_splitter` Python module](https://github.com/berkmancenter/mediacloud-sentence-splitter):

* Add more supported languages?

[`feed_seeker`](https://github.com/mitmedialab/feed_seeker):

* Fix https://github.com/mitmedialab/feed_seeker/issues/2 and https://github.com/mitmedialab/feed_seeker/issues/3?

**Comment by pypt** [comment]
Another idea for the Ultimate Sitemap Parser:

* Rewrite code to use asyncio: sitemap processing is mostly CPU-bound (all the XML parsing takes a lot of time), but asyncio might improve performance by something like 15%, and also would be useful when `Crawl-Delay` is defined in `robots.txt`

**Comment by pypt** [comment]
Another idea:

[readability-lxml](https://github.com/buriy/python-readability) is aging fast and is not necessarily still the best library around to extract body of the article from the HTML page. More and more articles get loaded using JavaScript due to an ongoing "frontend everywhere!" frenzy. Lastly, various CDNs, e.g. Cloudflare, are blocking our crawler just because our user agent doesn't have JavaScript enabled.

I think inevitably we'll have to switch to running a chromeless browser, loading each and every downloaded story in it, and then applying a well-supported third-party library, e.g. [Mozilla's Readability](https://github.com/mozilla/readability), to extract article title, author and body.

So, an experimental project for the student could be:

* Set up a chromeless browser
* Set up Readability
* Develop a HTTP service that accepts a parameter URL (and/or HTML body), loads it in the browser, runs Readability's magic, and returns the extracted HTML back to the requester.
* Package everything in a nice Docker image

There are similar projects like this, e.g. https://github.com/schollz/readable, so we'd need to do some research into whether such a thing exists already first.

**Comment by hroberts** [comment]
another idea:

Create scaffolding for a new version of our [api](https://github.com/berkmancenter/mediacloud/tree/release/doc/api_2_0_spec).  our existing api is written in perl, is inconsistent among its different major parts, and is goofily un-rest-ish in several places.  we would like to replace it with a python based api that uses a modern framework for api specification, implementation, and testing.

The work to replace the entire api is much too large for one summer, so this task would be to build enough of the end points to demonstrate how to apply the chosen framework to the problem.

**Comment by jhcccc** [comment]
> Another idea:
> 
> [readability-lxml](https://github.com/buriy/python-readability) is aging fast and is not necessarily still the best library around to extract body of the article from the HTML page. More and more articles get loaded using JavaScript due to an ongoing "frontend everywhere!" frenzy. Lastly, various CDNs, e.g. Cloudflare, are blocking our crawler just because our user agent doesn't have JavaScript enabled.
> 
> I think inevitably we'll have to switch to running a chromeless browser, loading each and every downloaded story in it, and then applying a well-supported third-party library, e.g. [Mozilla's Readability](https://github.com/mozilla/readability), to extract article title, author and body.
> 
> So, an experimental project for the student could be:
> 
> * Set up a chromeless browser
> * Set up Readability
> * Develop a HTTP service that accepts a parameter URL (and/or HTML body), loads it in the browser, runs Readability's magic, and returns the extracted HTML back to the requester.
> * Package everything in a nice Docker image
> 
> There are similar projects like this, e.g. https://github.com/schollz/readable, so we'd need to do some research into whether such a thing exists already first.

Hello pypt, 
I thought chromeless were deprecated. Have you considered Puppeteer or Selenium?

**Comment by pypt** [comment]
Hey @jhcccc! By "chromeless", I had a general browser without chrome (UI) in mind :) Which specific rendering engine (Gecko, WebKit) and/or tool to use for the task would be up to a student.

**Comment by pypt** [comment]
Final list:

https://docs.google.com/document/d/1GGbGtFOMS07dog4yzglY5hZCDc41ZQjY1RqRKOlW0B4/edit?usp=sharing

Sent it to Ellen and interested students.
