### ISSUE TITLE
INSTALLATION: TAST[system-packages : Install mecab-ipadic-neologd

### ISSUE THREAD

**Issue by frknasir** [berkmancenter/mediacloud#610]
During installation i get the following error....

TASK [system-packages : Install mecab-ipadic-neologd] *************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'mecab-ipadic-neologd' is available"}

How can I solve this? Thank you.

**Comment by pypt** [comment]
Hey Faruk, sorry for a late reply! We have since switched to running Media Cloud as Docker containers which should be more predictable. If you're still interested in running MC, please have a look at the new docs!
