### ISSUE TITLE
platform information is needed in snapshots in order to track changes

### ISSUE THREAD

**Issue by cindyloo** [berkmancenter/mediacloud#648]
all three platforms we are currently planning to support need to track changes from one version to the next
for open web:
seed_query/media/dates
for twitter:
seed_query/some combo of elite|crimson|other/dates
for reddit:
seed_query/subchannel/dates

**Comment by hroberts** [comment]
done.  see toipcs api spec under snapshots/list.  every snapshot now has a 'seed_queries' field that snapshots the current rows from topics, topics_media, topics_media_tags, and topic_seed_queries tables for that snapshot.
