### ISSUE TITLE
Clicking on word cloud in topic mapper presents page with no stories

### ISSUE THREAD

**Issue by aashkadave** [berkmancenter/mediacloud#654]
I'm going word-by-word into the word cloud for topic 3721 in order to look at the word in context models. For one of the words in the word cloud, "anti-muslim," I click through to find a screen that tells me there are no matching words in the topic: 

![Screen Shot 2020-01-08 at 4 12 40 PM](https://user-images.githubusercontent.com/31943908/72016874-981ccf80-3232-11ea-888d-d33a4d204400.png)

When I click through and inspect to see if there's an error, I do not get an error: 

![Screen Shot 2020-01-08 at 4 13 31 PM](https://user-images.githubusercontent.com/31943908/72016909-a834af00-3232-11ea-9744-2192d7dd3b93.png)

However, there should be word analysis for "anti-muslim" since a story search filter for that phrase returns over 2,000 stories within the topic: 

![Screen Shot 2020-01-08 at 4 13 59 PM](https://user-images.githubusercontent.com/31943908/72016968-bedb0600-3232-11ea-91ec-4e3136b26a74.png)

**Comment by hroberts** [comment]
moved to tools repo
