### ISSUE TITLE
can't change topic 'mode' via API

### ISSUE THREAD

**Issue by cindyloo** [berkmancenter/mediacloud#692]
mc.topicUpdate(2966, mode='web') doesn’t actually switch the mode to web

**Comment by hroberts** [comment]
why are you changing the mode of the topic?  that field is obsolete.  the
system now just produces the url_sharing foci for each topic that has
twitter, reddit, or generic_post topic seed queries.

-hal

**Comment by cindyloo** [comment]
ok, so we won't use it in the future at all? I created at least one topic with a mode = 'url_sharing' and wanted to change it. We can just delete that topic then? topic id 2966

**Comment by hroberts** [comment]
that is correct.  we will not use it in the future.  the same information
is in the 'focal_technique' field of the focal_set.  For normal foci
(subtopics), the focal_technique is 'Boolean Query'.  for the auto
generated co-sharing foci for seed queries, the focal_technique is 'URL
Sharing'.

-hal
