### ISSUE TITLE
if you have changes to platforms and to subtopics, subtopic changes are not integrated into the new version

### ISSUE THREAD

**Issue by cindyloo** [berkmancenter/mediacloud#693]
I added a MediaType subtopic to topic id 3910 and then generated a Version 4. It did not add it to the Topic, but still seems to have saved it as a subtopic as far as the focal 'set'(?) is concerned b/c it shows up as something to generate into Version 5.

**Comment by hroberts** [comment]
I'm having trouble understanding this.  When I look at Version 4, I see the Media Type:* subtopics in the filter options.  Why do you think that the subtopics did not get generated?  If you are just concerned about the orange "You've changed some subtoipcs ...' warning, I think that is getting triggered somehow by the auto generated URL Sharing subtopic.

**Comment by cindyloo** [comment]
The subtopics are not appearing on the topic platform, but they are there in the sense of querying for focal set definitions in the `ManageFocalSetsContainer`

**Comment by cindyloo** [comment]
found it in the front-end/python topics.py
https://github.com/mitmedialab/MediaCloud-Web-Tools/issues/1775
