### ISSUE TITLE
Adjust Solr's -Xmx and -Xms

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#714]
While playing around with Elasticsearch for logging (which is based on Lucene just like Solr), I found out that our `-Xmx` and `-Xms` set for Solr probably are not optimal. Currently [we set `-Xmx` to 90% of RAM allotted to the container](https://github.com/berkmancenter/mediacloud/blob/master/apps/solr-shard/bin/solr-shard.sh#L22-L24) and we don't set `-Xms` at all. As heap memory is not all that Solr uses, optimal memory limits are [a bit more difficult to calculate than that](https://blog.cloudera.com/apache-solr-memory-tuning-for-production/). I also have a suspicion that our occasional Solr request stalls might be related to this misconfiguration.

**Comment by hroberts** [comment]
The reason the max is set so high is that we had horrible problems with
solr running out of memory for a long time way back when we indexed
sentences.  Our hard experience is that solr does not sanely respect the
java max memory, but instead just crashes when more memory is used.  In any
case, looking at mcquery1, we are only using a 34G of RAM and 7G of swap on
mcquery1, with 100G used for fs buffers and 55G entirely free, so we're not
actually using anything like all of the memory on those machines, or even
all of available memory for buffer cache.

I think reducing the max to something like half of the available memory
would probably have no impact at all, but there is a risk as we lower the
limit that we will start to get the out of memory crashes again.

-hal

**Comment by pypt** [comment]
I've set `-Xms` to 40% of memory available to the container (which is 1/8th of host system's RAM), `-Xmx` to 70%, and made Solr write out a heapdump and crash on OOM exceptions instead of deciding to linger on without responding.

Closing for now, will reopen if we encounter any issues with this. Again, any improvements with Solr should be done after a 6.x -> 7.x -> 8.x upgrade because we're way behind major versions.

**Comment by pypt** [comment]
Some more background:

With `-Xms` set to 8192 MB, Solr correctly occupies around 9 GB of RAM:

```
ubuntu@mcec2query1:~$ ps auwx|egrep "MEM|38790"
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ubuntu    38790  9.1  6.1 189735904 10146940 ?  Sl   Aug10  78:04 java -server -Xmx14336m -Xms8192m -Djava.util.logging.config.file=file:///var/lib/solr/resources/log4j.properties -Djetty.base=/var/lib/solr -Djetty.home=/var/lib/solr -Djetty.port=8983 -Dsolr.solr.home=/var/lib/solr -Dsolr.data.dir=/var/lib/solr -Dsolr.log.dir=/var/lib/solr -Dhost=b663de0a2f01 -DzkHost=solr-zookeeper:2181 -DnumShards=24 -DzkClientTimeout=30000 -Dmediacloud.luceneMatchVersion=6.5.0 -XX:+UseContainerSupport -Dmediacloud.solr_dist_dir=/opt/solr -Dmediacloud.solr_webapp_dir=/opt/solr/server/solr-webapp -Ddisable.configEdit=true -jar start.jar --module=http
```

...but it doesn't seem that after a day of active use much of this heap space is actually used by something:

```
ubuntu@mcec2query1:~/jdk-12.0.2/bin$ sudo ./jhsdb jmap --heap --pid 38790
Attaching to process ID 38790, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 12.0.2+10

using thread-local object allocation.
Garbage-First (G1) GC with 4 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 40
   MaxHeapFreeRatio         = 70
   MaxHeapSize              = 15032385536 (14336.0MB)
   NewSize                  = 1363144 (1.2999954223632812MB)
   MaxNewSize               = 9017753600 (8600.0MB)
   OldSize                  = 5452592 (5.1999969482421875MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 4194304 (4.0MB)

Heap Usage:
G1 Heap:
   regions  = 3584
   capacity = 15032385536 (14336.0MB)
   used     = 1465724232 (1397.8235549926758MB)
   free     = 13566661304 (12938.176445007324MB)
   9.750443324446678% used
G1 Young Generation:
Eden Space:
   regions  = 45
   capacity = 1115684864 (1064.0MB)
   used     = 188743680 (180.0MB)
   free     = 926941184 (884.0MB)
   16.917293233082706% used
Survivor Space:
   regions  = 2
   capacity = 8388608 (8.0MB)
   used     = 8388608 (8.0MB)
   free     = 0 (0.0MB)
   100.0% used
G1 Old Generation:
   regions  = 306
   capacity = 7465861120 (7120.0MB)
   used     = 1268591944 (1209.8235549926758MB)
   free     = 6197269176 (5910.176445007324MB)
   16.99190386225668% used
```

```
ubuntu@mcec2query1:~/jdk-12.0.2/bin$ sudo ./jstat -gc 38790
 S0C    S1C    S0U    S1U      EC       EU        OC         OU       MC     MU    CCSC   CCSU   YGC     YGCT    FGC    FGCT    CGC    CGCT     GCT   
 0.0   8192.0  0.0   8192.0 1089536.0 376832.0 7290880.0  1238859.3  46000.0 44628.1 4864.0 4481.4    752   27.578   0      0.000  974     5.412   32.990
```

...and at this point Solr is already crashy.
