### ISSUE TITLE
All API endpoints returning Invalid API key error

### ISSUE THREAD

**Issue by esirK** [berkmancenter/mediacloud#722]
Hello.
I'm trying to access any API endpoint described here https://github.com/berkmancenter/mediacloud/blob/master/doc/api_2_0_spec/api_2_0_spec.md 
but all of them returns 
```
{
error: "Error(s): Invalid API key. All API keys were reset on May 1, 2020, so make sure you are using a new one.' "
}
```
I have created a user as described here https://github.com/berkmancenter/mediacloud/blob/master/doc/auth.markdown and I am using the user credentials to try and log in from the `api/v2/auth/login` endpoint. 
Quick question is there an API key that should be provided to the API endpoints including the login endpoint? And if so, which API key is it. 
Thank you.

**Comment by hroberts** [comment]
I think you'll have to run a query manually against postgres to get a valid
api key.  There's a bootstrap problem, in that the auth/login api end point
requires a functioning api key (it's purpose is to allow the front end
tools to validate login credentials).  Our assumption is that there is
already a functioning front end that the user can use to get the api key
via the profile page.  But that profile page requires an existing, valid
api key to execute the auth/login end point.

Here's an example of a session running the necessary query.  If you are
running media cloud, you are quickly going have to learn to how execute
commands in containers and specifically to run queries against the postgres
database in any case:

```
hroberts@mcdb1:~$ docker ps | grep sql-server
c818632af02f        dockermediacloud/postgresql-server:release
"/opt/mediacloud/bin…"   3 months ago        Up 3 months         5432/tcp
         mediacloud_postgresql-server.1.h7xv40youtudfqrep9p92lzs7
hroberts@mcdb1:~$ docker exec -it c818 bash
postgres@c818632af02f:/$ psql
psql (11.7 (Ubuntu 11.7-2.pgdg16.04+1))
Type "help" for help.

mediacloud=# select * from auth_user_api_keys limit 1;
 auth_user_ip_address_api_keys_id | auth_users_id |
    api_key                              | ip_address
----------------------------------+---------------+------------------------------------------------------------------+------------
                            12144 |         11154 |
THIS_IS_THE_KEY_YOU_NEED |
(1 row)
```

-hal

**Comment by esirK** [comment]
Thank you @hroberts for the prompt response. 
I have managed to get the key and login using the API. Also, [this](https://github.com/berkmancenter/mediacloud-web-tools) is the frontend I should set up for use with this backend right?

**Comment by pypt** [comment]
I think that specific link is a fork and https://github.com/mitmedialab/MediaCloud-Web-Tools is the original.

**Comment by esirK** [comment]
Thank you @pypt I will set that up.
