### ISSUE TITLE
recover solr disk space by removing stored sentences

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#77]
I have deployed code to stop storing sentences in solr.  This is mostly to clear up some disk space on the solr
servers but is also a small step toward story based indexing.

Word counting now fetches sentences from story_sentences based on the story_sentences_ids returned by solr.  Likewise for the wc/list api call.  Performance seems a little better than the direct solr word counting we were using (which was necessary for decent performance before we switch postgres to ssds).

To actually decrease existing space, we need to re-index the stories in our existing index.  I have added every stories_id to solr_import_extra_stories, which will cause a gradual re-indexing of all of our data.  In theory, this should decrease disk use over time as new, smaller segments are created and merged.  I am going to keep this issue open as I track progress of the re-index and its impact on disk space.

**Comment by pypt** [comment]
Probably obsolete now that the reindexing has been done and full story-based reimport is coming soon.
