### ISSUE TITLE
Refetch Bit.ly data for stories impacted by get_topic_url_variants() bug

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#97]
`get_topic_url_variants()` was giving out goofy URLs (fixed in fd91ea5bad59f27edfbc0abce9a3eb9bfeb61401, b07076cbb0b6bea58c8cb7de9ced79cabe571669), so Bit.ly click counts are likely to be skewed.

To-do:

- [x] stop Bit.ly fetchers
- [x] move current Bit.ly fetch queue somewhere
- [x] (re)enable versioning on Bit.ly S3 bucket (so that we don't have to download+backup old data)
- [x] delete raw Bit.ly data from S3 for affected stories
- [x] purge local Bit.ly S3 cache
- [ ] add affected stories back to Bit.ly fetcher queue
- [ ] restart fetchers to process the affected stories
- [ ] move old fetcher queue back to RabbitMQ
- [ ] clean up table from `scratch.*`

**Comment by pypt** [comment]
Currently removing raw Bit.ly data, purging Bit.ly cache.

**Comment by pypt** [comment]
Removed old data from S3, purged local cache, restarted fetchers.

Right now it seems that *too many* URL variants are being generated, so a small chunk of URLs are failing with:

* https://gist.github.com/pypt/6028aa8c576c124e51a0e3f526d82b38
* https://gist.github.com/pypt/c424d5d8d1682e2948eb8c7bcfda17b1

...but those are rare, so will ignore them for now.

**Comment by hroberts** [comment]
We need to refetch the facebook data as well.  Do we have to do a similar process for those jobs, or is re-adding the stories to the facebook_fetch_story_stats queue sufficient?

**Comment by pypt** [comment]
Only stats for an original story URL is being collected from Facebook, `all_url_variants()` is not called at all for whatever reason (IIRC part of the reason is that Facebook does a bunch of URL normalization on their side too).
